Data length change upon request
LBHackney-IT/addresses-api pull request #86
Opened 2021-01-11 14:37 UTC by humulla

Sandrine requested for three data to be removed from the national and Hackney address table and for some of the data lengths to be changed

I have made these changes which still allow the general functionality of the API to work

Let me know if you suggest any improvements

2021-01-11 15:29 UTC, crablab requested changes
I think for the `seed

2021-01-11 15:29 UTC, crablab commented on data/postgres/seed-dev-data.sql
> -COPY dbo.hackney_address (lpi_key, lpi_logical_status, lpi_start_date, lpi_end_date, lpi_last_update_date, usrn, uprn, parent_uprn, blpu_start_date, blpu_end_date, blpu_class, blpu_last_update_date,
So this will stop it copying data into those fields, but there will now be 3 extra columns in the actual data below :sweat_smile: 

I think the best thing would be to check with Sandrine and ask her to make up this seed data file again using the new schema (extended fields, and without these 3 columns), and replace this file with that :+1:

2024-05-08 08:24 UTC, adamtry submitted a review, later dismissed

2024-12-09 16:19 UTC, LBHTKarki commented
Closing this old PR as agreed.

2024-12-09 16:19 UTC, closed without merging